## German Wikipedia Heading Frequency

This notebook serves to sort German Wikipedia section headers by frequency as related to this [research project](https://meta.wikimedia.org/wiki/Research:Investigate_frequency_of_section_titles_in_5_large_Wikipedias).

In [1]:
import numpy as np
import pandas as pd

In [2]:
# read in headers file by chunks of 100000 to conserve memory
# https://stackoverflow.com/questions/25962114/how-to-read-a-6-gb-csv-file-with-pandas
tp = pd.read_csv('dewiki_20161101_headings.tsv', sep='\t', header=0, dtype={'page_id': np.int32, 'page_title': object, 'page_ns': np.int16, 'heading_level': np.int8, 'heading_text': object}, iterator=True, chunksize=100000)

In [3]:
# concatenate all rows where page_ns is equal to zero (article namespace) into a pandas dataframe
de_DF = pd.concat([chunk for chunk in tp])

In [4]:
de_DF.head()

,page_id,page_title,page_ns,heading_level,heading_text
0,1877065,Ndebele (Südafrika),0,2,Beschreibung und Geschichte
1,1877065,Ndebele (Südafrika),0,2,Sitten und Gebräuche
2,1877065,Ndebele (Südafrika),0,2,Weblinks
3,1877065,Ndebele (Südafrika),0,2,Einzelnachweise
4,1877069,Bitterlingsbarbe,0,2,Verbreitung

In [5]:
de_DF.page_ns.unique()

array([0])

In [6]:
# determine number of unique articles with sections
len(de_DF['page_title'].unique())

1720188

In [7]:
# remove leading and trailing whitespace from heading_text column
de_DF['heading_text'] = pd.core.strings.str_strip(de_DF['heading_text'])

In [8]:
# groupby heading_text and count the number of unique page_titles each heading appears in
# sort in descencing order
# this returns a pandas series object
article_count = de_DF.groupby('heading_text')['page_title'].apply(lambda x: len(x.unique())).sort_values(ascending=False)

In [9]:
# turn pandas series object into pandas dataframe
de_article_count_DF = pd.DataFrame({'section_title':article_count.index, 'number_of_articles':article_count.values})

In [10]:
# add a column for the percentage of articles that header appears in
de_article_count_DF['article_percentage'] = (de_article_count_DF['number_of_articles']/1993198)*100

In [11]:
# set pandas options to display 100 rows
# round percentage to 2 decimal places and show top 100 results
pd.options.display.max_rows = 100
de_article_count_DF.round({'article_percentage': 2}).head(100)

    number_of_articles                  section_title  article_percentage
0              1264341                       Weblinks               63.43
1               927206                Einzelnachweise               46.52
2               561161                      Literatur               28.15
3               297045                     Geschichte               14.90
4               260731                          Leben               13.08
5               182451                     Siehe auch                9.15
6                77984                        Quellen                3.91
7                59535                 Auszeichnungen                2.99
8                58265                       Karriere                2.92
9                57136                     Geographie                2.87
10               52287                          Werke                2.62
11               41956             Sehenswürdigkeiten                2.10
12               39863                       Handlung                2.00
13               37368                   Beschreibung                1.87
14               32937                      Geografie                1.65
15               32714                        Erfolge                1.64
16               32409                      Werdegang                1.63
17               31741                        Verkehr                1.59
18               30829                        Politik                1.55
19               30506                           Lage                1.53
20               29633                    Anmerkungen                1.49
21               29390                      Schriften                1.47
22               26893                    Diskografie                1.35
23               25463          Filmografie (Auswahl)                1.28
24               25257               Leben und Wirken                1.27
25               24853               Persönlichkeiten                1.25
26               22895        Bevölkerungsentwicklung                1.15
27               22372                       Ehrungen                1.12
28               22131                       Merkmale                1.11
29               20989                    Hintergrund                1.05
30               19607                      Sonstiges                0.98
31               18908                      Biografie                0.95
32               18601                Werke (Auswahl)                0.93
33               18322                         Kritik                0.92
34               17796                         Wappen                0.89
35               17678                    Filmografie                0.89
36               17443                       Fußnoten                0.88
37               17432                     Wirtschaft                0.87
38               17397                      Rezeption                0.87
39               16517                    Bevölkerung                0.83
40               16150                        Familie                0.81
41               15994                         Belege                0.80
42               15398             Veröffentlichungen                0.77
43               15353   Wirtschaft und Infrastruktur                0.77
44               14703                       Kritiken                0.74
45               14246  Kultur und Sehenswürdigkeiten                0.71
46               13690                 Leben und Werk                0.69
47               13453                     Systematik                0.67
48               13037             Nationalmannschaft                0.65
49               12934                         Inhalt                0.65
50               12518                           Werk                0.63
51               12008                    Verbreitung                0.60
52               11511            Schriften (Auswahl)                0.58
53               11418                     Ergebnisse                0.57
54               10746                          Alben                0.54
55               10700             Geographische Lage                0.54
56               10217                    Lebensweise                0.51
57               10022           Einwohnerentwicklung                0.50
58                9691                        Verlauf                0.49
59                9583                         Quelle                0.48
60                9569                        Singles                0.48
61                9549                     Referenzen                0.48
62                9323    Söhne und Töchter der Stadt                0.47
63                9286                     Verwendung                0.47
64                9161                      Vorkommen                0.46
65                9071                         Trivia                0.46
66                9058                        Weblink                0.45
67                8953                  Eigenschaften                0.45
68                8855                    Architektur                0.44
69                8192             Gemeindegliederung                0.41
70                8002                        Bildung                0.40
71                7902                      Nachweise                0.40
72                7870               Technische Daten                0.39
73                7704                          Sport                0.39
74                7698                  Publikationen                0.39
75                7664     Erfolge und Auszeichnungen                0.38
76                7539                     Entstehung                0.38
77                7435                    Ausstattung                0.37
78                7408                      Statistik                0.37
79                7302                        Galerie                0.37
80                7295                  Vorgeschichte                0.37
81                7276                       Privates                0.37
82                7198                       Bauwerke                0.36
83                7087                         Finale                0.36
84                6887                     Titelliste                0.35
85                6857                         Verein                0.34
86                6631                          Modus                0.33
87                6577                     Produktion                0.33
88                6541                  International                0.33
89                6520                    Allgemeines                0.33
90                6465                        Vereine                0.32
91                6461                      Bedeutung                0.32
92                6461                       Herkunft                0.32
93                6233                      Gemeinden                0.31
94                6226          Städtepartnerschaften                0.31
95                6091                         Bilder                0.31
96                6070                         Einzel                0.30
97                6018             Leben und Karriere                0.30
98                5972                    Gemeinderat                0.30
99                5923                      Setzliste                0.30