## English Wikipedia Heading Frequency

This notebook serves to sort English Wikipedia section headers by frequency as related to this [research project](https://meta.wikimedia.org/wiki/Research:Investigate_frequency_of_section_titles_in_5_large_Wikipedias).

In [1]:
import numpy as np
import pandas as pd

In [2]:
# read in headers file by chunks of 100000 to conserve memory
# https://stackoverflow.com/questions/25962114/how-to-read-a-6-gb-csv-file-with-pandas
en_DF = pd.read_csv('enwiki_20161101_headings.tsv', sep='\t', header=0, dtype={'page_id': np.int32, 'page_title': object, 'page_ns': np.int16, 'heading_level': np.int8, 'heading_text': object})

In [3]:
en_DF.head()

   page_id       page_title  page_ns  heading_level      heading_text
0  3926881  Slab allocation        0              2            Basis
1  3926881  Slab allocation        0              2   Implementation
2  3926881  Slab allocation        0              2             Slabs
3  3926881  Slab allocation        0              3       Large slabs
4  3926881  Slab allocation        0              3       Small slabs

In [4]:
en_DF.page_ns.unique()

array([0])

In [5]:
# determine number of unique articles
len(en_DF.page_title.unique())

4947256

In [6]:
# remove leading and trailing whitespace from heading_text column
en_DF['heading_text'] = pd.core.strings.str_strip(en_DF['heading_text'])

In [7]:
# groupby heading_text and count the number of unique page_titles each heading appears in
# sort in descencing order
# this returns a pandas series object
article_count = en_DF.groupby('heading_text')['page_title'].apply(lambda x: len(x.unique())).sort_values(ascending=False)

In [8]:
# turn pandas series object into pandas dataframe
en_article_count_DF = pd.DataFrame({'section_title':article_count.index, 'number_of_articles':article_count.values})

In [9]:
en_article_count_DF.head()

   number_of_articles   section_title
0             4124326      References
1             2338241  External links
2             1134485        See also
3              533348         History
4              283198           Notes

In [10]:
# add a column for the percentage of articles that header appears in
en_article_count_DF['article_percentage'] = (en_article_count_DF['number_of_articles']/5275388)*100

In [11]:
# set pandas options to display 100 rows
# round percentage to 2 decimal places and show top 100 results
pd.options.display.max_rows = 100
en_article_count_DF.round({'article_percentage': 2}).head(100)

    number_of_articles             section_title  article_percentage
0              4124326                References               78.18
1              2338241            External links               44.32
2              1134485                  See also               21.51
3               533348                   History               10.11
4               283198                     Notes                5.37
5               176414                    Career                3.34
6               152419                 Biography                2.89
7               148147           Further reading                2.81
8               145080             Track listing                2.75
9               122409              Bibliography                2.32
10              114524                   Sources                2.17
11              109969                Early life                2.08
12              109283                      Cast                2.07
13              106474                 Geography                2.02
14               98877             Personal life                1.87
15               94721                Background                1.80
16               94700                      Plot                1.80
17               86586                 Reception                1.64
18               80893               Description                1.53
19               79195               Discography                1.50
20               77524              Demographics                1.47
21               76763                    Awards                1.46
22               75458                 Personnel                1.43
23               63229                 Education                1.20
24               58441                   Results                1.11
25               56589               Filmography                1.07
26               52225                      Life                0.99
27               52184                   Honours                0.99
28               48518                Production                0.92
29               47708                     Works                0.90
30               44541                   Gallery                0.84
31               38914                  Overview                0.74
32               38520                   Singles                0.73
33               36777                 Footnotes                0.70
34               35895                     Death                0.68
35               34111                    Charts                0.65
36               32766              Distribution                0.62
37               30184                Population                0.57
38               29925              Publications                0.57
39               29671                    Legacy                0.56
40               29255                    Family                0.55
41               26883                     Music                0.51
42               26721               Club career                0.51
43               26526  Early life and education                0.50
44               26443                Television                0.50
45               26327                   Species                0.50
46               26264                    Events                0.50
47               26204                     Final                0.50
48               25778                     Books                0.49
49               25296        Critical reception                0.48
50               25235                    Albums                0.48
51               25107                   Economy                0.48
52               24925               Early years                0.47
53               24558                  Location                0.47
54               24462      International career                0.46
55               23877                  Schedule                0.45
56               23753       Professional career                0.45
57               22716         Career statistics                0.43
58               22159            Notable people                0.42
59               21120                 Etymology                0.40
60               21086      Notes and references                0.40
61               21030                  Synopsis                0.40
62               20969            Playing career                0.40
63               20652         Chart performance                0.39
64               19545               Development                0.37
65               19509                   Climate                0.37
66               19497          Political career                0.37
67               19445            Transportation                0.37
68               18834                  Politics                0.36
69               18719                     Other                0.35
70               18471                   Release                0.35
71               18403                      Film                0.35
72               18204           Life and career                0.35
73               18077                 Aftermath                0.34
74               18077                    People                0.34
75               17479                    Deaths                0.33
76               17385                Soundtrack                0.33
77               17352              Early career                0.33
78               17257                 Citations                0.33
79               17079                 Transport                0.32
80               16923               Music video                0.32
81               16085    Awards and nominations                0.30
82               15992                   Members                0.30
83               15954                    Births                0.30
84               15908                      Club                0.30
85               15612                Statistics                0.30
86               15606      Selected filmography                0.30
87               15427        In popular culture                0.29
88               15374                  Episodes                0.29
89               15268                Literature                0.29
90               15242                  Gameplay                0.29
91               15132              Plot summary                0.29
92               15112                Characters                0.29
93               15105            Regular season                0.29
94               14784                     Seeds                0.28
95               14574                    Places                0.28
96               14310            Notable alumni                0.27
97               14302                    Sports                0.27
98               14131                    Roster                0.27
99               13848           Release history                0.26